/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageDependencyChild
 */
@JsonPropertyOrder({
  CoverageDependencyChild.JSON_PROPERTY_ITEM_IDENTIFIER,
  CoverageDependencyChild.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  CoverageDependencyChild.JSON_PROPERTY_COVERAGE_CODE,
  CoverageDependencyChild.JSON_PROPERTY_COVERAGE_DEPENDENCY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class CoverageDependencyChild {
  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COVERAGE_CODE = "coverageCode";
  private String coverageCode;

  public static final String JSON_PROPERTY_COVERAGE_DEPENDENCY = "coverageDependency";
  private JsonNullable<String> coverageDependency = JsonNullable.<String>undefined();


  public CoverageDependencyChild itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public CoverageDependencyChild ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public CoverageDependencyChild coverageCode(String coverageCode) {
    
    this.coverageCode = coverageCode;
    return this;
  }

   /**
   * Get coverageCode
   * @return coverageCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COVERAGE_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getCoverageCode() {
    return coverageCode;
  }


  public void setCoverageCode(String coverageCode) {
    this.coverageCode = coverageCode;
  }


  public CoverageDependencyChild coverageDependency(String coverageDependency) {
    this.coverageDependency = JsonNullable.<String>of(coverageDependency);
    
    return this;
  }

   /**
   * Get coverageDependency
   * @return coverageDependency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getCoverageDependency() {
        return coverageDependency.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COVERAGE_DEPENDENCY)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getCoverageDependency_JsonNullable() {
    return coverageDependency;
  }
  
  @JsonProperty(JSON_PROPERTY_COVERAGE_DEPENDENCY)
  public void setCoverageDependency_JsonNullable(JsonNullable<String> coverageDependency) {
    this.coverageDependency = coverageDependency;
  }

  public void setCoverageDependency(String coverageDependency) {
    this.coverageDependency = JsonNullable.<String>of(coverageDependency);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageDependencyChild coverageDependencyChild = (CoverageDependencyChild) o;
    return Objects.equals(this.itemIdentifier, coverageDependencyChild.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, coverageDependencyChild.ancestorItemIdentifier) &&
        Objects.equals(this.coverageCode, coverageDependencyChild.coverageCode) &&
        Objects.equals(this.coverageDependency, coverageDependencyChild.coverageDependency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIdentifier, ancestorItemIdentifier, coverageCode, coverageDependency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageDependencyChild {\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    coverageCode: ").append(toIndentedString(coverageCode)).append("\n");
    sb.append("    coverageDependency: ").append(toIndentedString(coverageDependency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

