/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ExternalAttributeValue
 */
@JsonPropertyOrder({
  ExternalAttributeValue.JSON_PROPERTY_ITEM_IDENTIFIER,
  ExternalAttributeValue.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  ExternalAttributeValue.JSON_PROPERTY_ATTRIBUTE_NAME,
  ExternalAttributeValue.JSON_PROPERTY_ATTRIBUTE_VALUE,
  ExternalAttributeValue.JSON_PROPERTY_ENTITY_NAME,
  ExternalAttributeValue.JSON_PROPERTY_DISPLAY_VALUE,
  ExternalAttributeValue.JSON_PROPERTY_PRIORITY,
  ExternalAttributeValue.JSON_PROPERTY_TYPELIST_NAME,
  ExternalAttributeValue.JSON_PROPERTY_VALUE_TYPE,
  ExternalAttributeValue.JSON_PROPERTY_EXTERNAL_PRODUCT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class ExternalAttributeValue {
  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ATTRIBUTE_NAME = "attributeName";
  private String attributeName;

  public static final String JSON_PROPERTY_ATTRIBUTE_VALUE = "attributeValue";
  private String attributeValue;

  public static final String JSON_PROPERTY_ENTITY_NAME = "entityName";
  private String entityName;

  public static final String JSON_PROPERTY_DISPLAY_VALUE = "displayValue";
  private String displayValue;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private JsonNullable<Integer> priority = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TYPELIST_NAME = "typelistName";
  private String typelistName;

  /**
   * Gets or Sets valueType
   */
  public enum ValueTypeEnum {
    STRING("string"),
    
    OBJECT("object"),
    
    CALCULATED("calculated"),
    
    OTHER("other"),
    
    LIST("list"),
    
    STRING_MULTILINE("string_multiline"),
    
    BOOLEAN("boolean"),
    
    INTEGER("integer"),
    
    INTEGER_RANGE("integer_range"),
    
    INTEGER_SET("integer_set"),
    
    MONEY_RANGE("money_range"),
    
    MONEY_SET("money_set"),
    
    LONG("long"),
    
    DECIMAL("decimal"),
    
    DATE("date"),
    
    MONEY("money"),
    
    TYPEKEY("typekey"),
    
    OPTION("option"),
    
    LABEL("label"),
    
    LOCATION("location"),
    
    MONEY_USD("money_usd"),
    
    MONEY_EUR("money_eur"),
    
    MONEY_GBP("money_gbp"),
    
    PERCENT("percent"),
    
    PERCENTDEC("percentdec"),
    
    YEAR("year"),
    
    ADDRESS("address"),
    
    AFPFUNCTION("afpfunction");

    private String value;

    ValueTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueTypeEnum fromValue(String value) {
      for (ValueTypeEnum b : ValueTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_VALUE_TYPE = "valueType";
  private JsonNullable<ValueTypeEnum> valueType = JsonNullable.<ValueTypeEnum>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_PRODUCT = "externalProduct";
  private JsonNullable<String> externalProduct = JsonNullable.<String>undefined();


  public ExternalAttributeValue itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public ExternalAttributeValue ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public ExternalAttributeValue attributeName(String attributeName) {
    
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Get attributeName
   * @return attributeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getAttributeName() {
    return attributeName;
  }


  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }


  public ExternalAttributeValue attributeValue(String attributeValue) {
    
    this.attributeValue = attributeValue;
    return this;
  }

   /**
   * Get attributeValue
   * @return attributeValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_VALUE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getAttributeValue() {
    return attributeValue;
  }


  public void setAttributeValue(String attributeValue) {
    this.attributeValue = attributeValue;
  }


  public ExternalAttributeValue entityName(String entityName) {
    
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENTITY_NAME)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getEntityName() {
    return entityName;
  }


  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }


  public ExternalAttributeValue displayValue(String displayValue) {
    
    this.displayValue = displayValue;
    return this;
  }

   /**
   * Get displayValue
   * @return displayValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_VALUE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getDisplayValue() {
    return displayValue;
  }


  public void setDisplayValue(String displayValue) {
    this.displayValue = displayValue;
  }


  public ExternalAttributeValue priority(Integer priority) {
    this.priority = JsonNullable.<Integer>of(priority);
    
    return this;
  }

   /**
   * Get priority
   * minimum: -2147483648
   * maximum: 2147483647
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getPriority() {
        return priority.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<Integer> getPriority_JsonNullable() {
    return priority;
  }
  
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  public void setPriority_JsonNullable(JsonNullable<Integer> priority) {
    this.priority = priority;
  }

  public void setPriority(Integer priority) {
    this.priority = JsonNullable.<Integer>of(priority);
  }


  public ExternalAttributeValue typelistName(String typelistName) {
    
    this.typelistName = typelistName;
    return this;
  }

   /**
   * Get typelistName
   * @return typelistName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPELIST_NAME)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getTypelistName() {
    return typelistName;
  }


  public void setTypelistName(String typelistName) {
    this.typelistName = typelistName;
  }


  public ExternalAttributeValue valueType(ValueTypeEnum valueType) {
    this.valueType = JsonNullable.<ValueTypeEnum>of(valueType);
    
    return this;
  }

   /**
   * Get valueType
   * @return valueType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public ValueTypeEnum getValueType() {
        return valueType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VALUE_TYPE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<ValueTypeEnum> getValueType_JsonNullable() {
    return valueType;
  }
  
  @JsonProperty(JSON_PROPERTY_VALUE_TYPE)
  public void setValueType_JsonNullable(JsonNullable<ValueTypeEnum> valueType) {
    this.valueType = valueType;
  }

  public void setValueType(ValueTypeEnum valueType) {
    this.valueType = JsonNullable.<ValueTypeEnum>of(valueType);
  }


  public ExternalAttributeValue externalProduct(String externalProduct) {
    this.externalProduct = JsonNullable.<String>of(externalProduct);
    
    return this;
  }

   /**
   * Get externalProduct
   * @return externalProduct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getExternalProduct() {
        return externalProduct.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getExternalProduct_JsonNullable() {
    return externalProduct;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PRODUCT)
  public void setExternalProduct_JsonNullable(JsonNullable<String> externalProduct) {
    this.externalProduct = externalProduct;
  }

  public void setExternalProduct(String externalProduct) {
    this.externalProduct = JsonNullable.<String>of(externalProduct);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAttributeValue externalAttributeValue = (ExternalAttributeValue) o;
    return Objects.equals(this.itemIdentifier, externalAttributeValue.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, externalAttributeValue.ancestorItemIdentifier) &&
        Objects.equals(this.attributeName, externalAttributeValue.attributeName) &&
        Objects.equals(this.attributeValue, externalAttributeValue.attributeValue) &&
        Objects.equals(this.entityName, externalAttributeValue.entityName) &&
        Objects.equals(this.displayValue, externalAttributeValue.displayValue) &&
        Objects.equals(this.priority, externalAttributeValue.priority) &&
        Objects.equals(this.typelistName, externalAttributeValue.typelistName) &&
        Objects.equals(this.valueType, externalAttributeValue.valueType) &&
        Objects.equals(this.externalProduct, externalAttributeValue.externalProduct);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIdentifier, ancestorItemIdentifier, attributeName, attributeValue, entityName, displayValue, priority, typelistName, valueType, externalProduct);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAttributeValue {\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    attributeValue: ").append(toIndentedString(attributeValue)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    displayValue: ").append(toIndentedString(displayValue)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    typelistName: ").append(toIndentedString(typelistName)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    externalProduct: ").append(toIndentedString(externalProduct)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

