/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import pmp.sdk.model.ItemLinkDefinitionDetail;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ItemLinkDetail
 */
@JsonPropertyOrder({
  ItemLinkDetail.JSON_PROPERTY_ID,
  ItemLinkDetail.JSON_PROPERTY_ITEM_LINK_DEFINITION_DETAIL,
  ItemLinkDetail.JSON_PROPERTY_VALUE,
  ItemLinkDetail.JSON_PROPERTY_ITEM_LINK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class ItemLinkDetail {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_ITEM_LINK_DEFINITION_DETAIL = "itemLinkDefinitionDetail";
  private ItemLinkDefinitionDetail itemLinkDefinitionDetail;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public static final String JSON_PROPERTY_ITEM_LINK = "itemLink";
  private Integer itemLink;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Integer getId() {
    return id;
  }




  public ItemLinkDetail itemLinkDefinitionDetail(ItemLinkDefinitionDetail itemLinkDefinitionDetail) {
    
    this.itemLinkDefinitionDetail = itemLinkDefinitionDetail;
    return this;
  }

   /**
   * Get itemLinkDefinitionDetail
   * @return itemLinkDefinitionDetail
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_LINK_DEFINITION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemLinkDefinitionDetail getItemLinkDefinitionDetail() {
    return itemLinkDefinitionDetail;
  }


  public void setItemLinkDefinitionDetail(ItemLinkDefinitionDetail itemLinkDefinitionDetail) {
    this.itemLinkDefinitionDetail = itemLinkDefinitionDetail;
  }


  public ItemLinkDetail value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public ItemLinkDetail itemLink(Integer itemLink) {
    
    this.itemLink = itemLink;
    return this;
  }

   /**
   * Get itemLink
   * @return itemLink
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getItemLink() {
    return itemLink;
  }


  public void setItemLink(Integer itemLink) {
    this.itemLink = itemLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemLinkDetail itemLinkDetail = (ItemLinkDetail) o;
    return Objects.equals(this.id, itemLinkDetail.id) &&
        Objects.equals(this.itemLinkDefinitionDetail, itemLinkDetail.itemLinkDefinitionDetail) &&
        Objects.equals(this.value, itemLinkDetail.value) &&
        Objects.equals(this.itemLink, itemLinkDetail.itemLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, itemLinkDefinitionDetail, value, itemLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemLinkDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemLinkDefinitionDetail: ").append(toIndentedString(itemLinkDefinitionDetail)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    itemLink: ").append(toIndentedString(itemLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

