/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import pmp.sdk.model.ItemLinkDetail;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ItemLink
 */
@JsonPropertyOrder({
  ItemLink.JSON_PROPERTY_ID,
  ItemLink.JSON_PROPERTY_ITEM_LINK_DETAILS,
  ItemLink.JSON_PROPERTY_PARENT_TYPE,
  ItemLink.JSON_PROPERTY_PARENT_CODE,
  ItemLink.JSON_PROPERTY_PARENT_SUB_CODE,
  ItemLink.JSON_PROPERTY_PARENT_VERSION_NUMBER,
  ItemLink.JSON_PROPERTY_PARENT_ITEM_IDENTIFIER,
  ItemLink.JSON_PROPERTY_PARENT_SECONDARY_IDENTIFIER,
  ItemLink.JSON_PROPERTY_PARENT_PUBLIC_I_D,
  ItemLink.JSON_PROPERTY_CHILD_TYPE,
  ItemLink.JSON_PROPERTY_CHILD_CODE,
  ItemLink.JSON_PROPERTY_CHILD_SUB_CODE,
  ItemLink.JSON_PROPERTY_CHILD_VERSION_NUMBER,
  ItemLink.JSON_PROPERTY_CHILD_ITEM_IDENTIFIER,
  ItemLink.JSON_PROPERTY_CHILD_SECONDARY_IDENTIFIER,
  ItemLink.JSON_PROPERTY_CHILD_PUBLIC_I_D,
  ItemLink.JSON_PROPERTY_REMOVED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class ItemLink {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_ITEM_LINK_DETAILS = "itemLinkDetails";
  private List<ItemLinkDetail> itemLinkDetails = new ArrayList<>();

  public static final String JSON_PROPERTY_PARENT_TYPE = "parentType";
  private String parentType;

  public static final String JSON_PROPERTY_PARENT_CODE = "parentCode";
  private String parentCode;

  public static final String JSON_PROPERTY_PARENT_SUB_CODE = "parentSubCode";
  private String parentSubCode;

  public static final String JSON_PROPERTY_PARENT_VERSION_NUMBER = "parentVersionNumber";
  private JsonNullable<Integer> parentVersionNumber = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PARENT_ITEM_IDENTIFIER = "parentItemIdentifier";
  private String parentItemIdentifier;

  public static final String JSON_PROPERTY_PARENT_SECONDARY_IDENTIFIER = "parentSecondaryIdentifier";
  private String parentSecondaryIdentifier;

  public static final String JSON_PROPERTY_PARENT_PUBLIC_I_D = "parentPublicID";
  private String parentPublicID;

  public static final String JSON_PROPERTY_CHILD_TYPE = "childType";
  private String childType;

  public static final String JSON_PROPERTY_CHILD_CODE = "childCode";
  private String childCode;

  public static final String JSON_PROPERTY_CHILD_SUB_CODE = "childSubCode";
  private String childSubCode;

  public static final String JSON_PROPERTY_CHILD_VERSION_NUMBER = "childVersionNumber";
  private JsonNullable<Integer> childVersionNumber = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CHILD_ITEM_IDENTIFIER = "childItemIdentifier";
  private String childItemIdentifier;

  public static final String JSON_PROPERTY_CHILD_SECONDARY_IDENTIFIER = "childSecondaryIdentifier";
  private String childSecondaryIdentifier;

  public static final String JSON_PROPERTY_CHILD_PUBLIC_I_D = "childPublicID";
  private String childPublicID;

  public static final String JSON_PROPERTY_REMOVED = "removed";
  private Boolean removed;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Integer getId() {
    return id;
  }




  public ItemLink itemLinkDetails(List<ItemLinkDetail> itemLinkDetails) {
    
    this.itemLinkDetails = itemLinkDetails;
    return this;
  }

  public ItemLink addItemLinkDetailsItem(ItemLinkDetail itemLinkDetailsItem) {
    this.itemLinkDetails.add(itemLinkDetailsItem);
    return this;
  }

   /**
   * Get itemLinkDetails
   * @return itemLinkDetails
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_LINK_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ItemLinkDetail> getItemLinkDetails() {
    return itemLinkDetails;
  }


  public void setItemLinkDetails(List<ItemLinkDetail> itemLinkDetails) {
    this.itemLinkDetails = itemLinkDetails;
  }


  public ItemLink parentType(String parentType) {
    
    this.parentType = parentType;
    return this;
  }

   /**
   * Get parentType
   * @return parentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentType() {
    return parentType;
  }


  public void setParentType(String parentType) {
    this.parentType = parentType;
  }


  public ItemLink parentCode(String parentCode) {
    
    this.parentCode = parentCode;
    return this;
  }

   /**
   * Get parentCode
   * @return parentCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentCode() {
    return parentCode;
  }


  public void setParentCode(String parentCode) {
    this.parentCode = parentCode;
  }


  public ItemLink parentSubCode(String parentSubCode) {
    
    this.parentSubCode = parentSubCode;
    return this;
  }

   /**
   * Get parentSubCode
   * @return parentSubCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_SUB_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentSubCode() {
    return parentSubCode;
  }


  public void setParentSubCode(String parentSubCode) {
    this.parentSubCode = parentSubCode;
  }


  public ItemLink parentVersionNumber(Integer parentVersionNumber) {
    this.parentVersionNumber = JsonNullable.<Integer>of(parentVersionNumber);
    
    return this;
  }

   /**
   * Get parentVersionNumber
   * minimum: -2147483648
   * maximum: 2147483647
   * @return parentVersionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getParentVersionNumber() {
        return parentVersionNumber.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARENT_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<Integer> getParentVersionNumber_JsonNullable() {
    return parentVersionNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_PARENT_VERSION_NUMBER)
  public void setParentVersionNumber_JsonNullable(JsonNullable<Integer> parentVersionNumber) {
    this.parentVersionNumber = parentVersionNumber;
  }

  public void setParentVersionNumber(Integer parentVersionNumber) {
    this.parentVersionNumber = JsonNullable.<Integer>of(parentVersionNumber);
  }


  public ItemLink parentItemIdentifier(String parentItemIdentifier) {
    
    this.parentItemIdentifier = parentItemIdentifier;
    return this;
  }

   /**
   * Get parentItemIdentifier
   * @return parentItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentItemIdentifier() {
    return parentItemIdentifier;
  }


  public void setParentItemIdentifier(String parentItemIdentifier) {
    this.parentItemIdentifier = parentItemIdentifier;
  }


  public ItemLink parentSecondaryIdentifier(String parentSecondaryIdentifier) {
    
    this.parentSecondaryIdentifier = parentSecondaryIdentifier;
    return this;
  }

   /**
   * Get parentSecondaryIdentifier
   * @return parentSecondaryIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_SECONDARY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentSecondaryIdentifier() {
    return parentSecondaryIdentifier;
  }


  public void setParentSecondaryIdentifier(String parentSecondaryIdentifier) {
    this.parentSecondaryIdentifier = parentSecondaryIdentifier;
  }


  public ItemLink parentPublicID(String parentPublicID) {
    
    this.parentPublicID = parentPublicID;
    return this;
  }

   /**
   * Get parentPublicID
   * @return parentPublicID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_PUBLIC_I_D)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getParentPublicID() {
    return parentPublicID;
  }


  public void setParentPublicID(String parentPublicID) {
    this.parentPublicID = parentPublicID;
  }


  public ItemLink childType(String childType) {
    
    this.childType = childType;
    return this;
  }

   /**
   * Get childType
   * @return childType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_TYPE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildType() {
    return childType;
  }


  public void setChildType(String childType) {
    this.childType = childType;
  }


  public ItemLink childCode(String childCode) {
    
    this.childCode = childCode;
    return this;
  }

   /**
   * Get childCode
   * @return childCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildCode() {
    return childCode;
  }


  public void setChildCode(String childCode) {
    this.childCode = childCode;
  }


  public ItemLink childSubCode(String childSubCode) {
    
    this.childSubCode = childSubCode;
    return this;
  }

   /**
   * Get childSubCode
   * @return childSubCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_SUB_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildSubCode() {
    return childSubCode;
  }


  public void setChildSubCode(String childSubCode) {
    this.childSubCode = childSubCode;
  }


  public ItemLink childVersionNumber(Integer childVersionNumber) {
    this.childVersionNumber = JsonNullable.<Integer>of(childVersionNumber);
    
    return this;
  }

   /**
   * Get childVersionNumber
   * minimum: -2147483648
   * maximum: 2147483647
   * @return childVersionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getChildVersionNumber() {
        return childVersionNumber.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHILD_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<Integer> getChildVersionNumber_JsonNullable() {
    return childVersionNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_CHILD_VERSION_NUMBER)
  public void setChildVersionNumber_JsonNullable(JsonNullable<Integer> childVersionNumber) {
    this.childVersionNumber = childVersionNumber;
  }

  public void setChildVersionNumber(Integer childVersionNumber) {
    this.childVersionNumber = JsonNullable.<Integer>of(childVersionNumber);
  }


  public ItemLink childItemIdentifier(String childItemIdentifier) {
    
    this.childItemIdentifier = childItemIdentifier;
    return this;
  }

   /**
   * Get childItemIdentifier
   * @return childItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildItemIdentifier() {
    return childItemIdentifier;
  }


  public void setChildItemIdentifier(String childItemIdentifier) {
    this.childItemIdentifier = childItemIdentifier;
  }


  public ItemLink childSecondaryIdentifier(String childSecondaryIdentifier) {
    
    this.childSecondaryIdentifier = childSecondaryIdentifier;
    return this;
  }

   /**
   * Get childSecondaryIdentifier
   * @return childSecondaryIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_SECONDARY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildSecondaryIdentifier() {
    return childSecondaryIdentifier;
  }


  public void setChildSecondaryIdentifier(String childSecondaryIdentifier) {
    this.childSecondaryIdentifier = childSecondaryIdentifier;
  }


  public ItemLink childPublicID(String childPublicID) {
    
    this.childPublicID = childPublicID;
    return this;
  }

   /**
   * Get childPublicID
   * @return childPublicID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILD_PUBLIC_I_D)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getChildPublicID() {
    return childPublicID;
  }


  public void setChildPublicID(String childPublicID) {
    this.childPublicID = childPublicID;
  }


  public ItemLink removed(Boolean removed) {
    
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REMOVED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getRemoved() {
    return removed;
  }


  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemLink itemLink = (ItemLink) o;
    return Objects.equals(this.id, itemLink.id) &&
        Objects.equals(this.itemLinkDetails, itemLink.itemLinkDetails) &&
        Objects.equals(this.parentType, itemLink.parentType) &&
        Objects.equals(this.parentCode, itemLink.parentCode) &&
        Objects.equals(this.parentSubCode, itemLink.parentSubCode) &&
        Objects.equals(this.parentVersionNumber, itemLink.parentVersionNumber) &&
        Objects.equals(this.parentItemIdentifier, itemLink.parentItemIdentifier) &&
        Objects.equals(this.parentSecondaryIdentifier, itemLink.parentSecondaryIdentifier) &&
        Objects.equals(this.parentPublicID, itemLink.parentPublicID) &&
        Objects.equals(this.childType, itemLink.childType) &&
        Objects.equals(this.childCode, itemLink.childCode) &&
        Objects.equals(this.childSubCode, itemLink.childSubCode) &&
        Objects.equals(this.childVersionNumber, itemLink.childVersionNumber) &&
        Objects.equals(this.childItemIdentifier, itemLink.childItemIdentifier) &&
        Objects.equals(this.childSecondaryIdentifier, itemLink.childSecondaryIdentifier) &&
        Objects.equals(this.childPublicID, itemLink.childPublicID) &&
        Objects.equals(this.removed, itemLink.removed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, itemLinkDetails, parentType, parentCode, parentSubCode, parentVersionNumber, parentItemIdentifier, parentSecondaryIdentifier, parentPublicID, childType, childCode, childSubCode, childVersionNumber, childItemIdentifier, childSecondaryIdentifier, childPublicID, removed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemLink {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemLinkDetails: ").append(toIndentedString(itemLinkDetails)).append("\n");
    sb.append("    parentType: ").append(toIndentedString(parentType)).append("\n");
    sb.append("    parentCode: ").append(toIndentedString(parentCode)).append("\n");
    sb.append("    parentSubCode: ").append(toIndentedString(parentSubCode)).append("\n");
    sb.append("    parentVersionNumber: ").append(toIndentedString(parentVersionNumber)).append("\n");
    sb.append("    parentItemIdentifier: ").append(toIndentedString(parentItemIdentifier)).append("\n");
    sb.append("    parentSecondaryIdentifier: ").append(toIndentedString(parentSecondaryIdentifier)).append("\n");
    sb.append("    parentPublicID: ").append(toIndentedString(parentPublicID)).append("\n");
    sb.append("    childType: ").append(toIndentedString(childType)).append("\n");
    sb.append("    childCode: ").append(toIndentedString(childCode)).append("\n");
    sb.append("    childSubCode: ").append(toIndentedString(childSubCode)).append("\n");
    sb.append("    childVersionNumber: ").append(toIndentedString(childVersionNumber)).append("\n");
    sb.append("    childItemIdentifier: ").append(toIndentedString(childItemIdentifier)).append("\n");
    sb.append("    childSecondaryIdentifier: ").append(toIndentedString(childSecondaryIdentifier)).append("\n");
    sb.append("    childPublicID: ").append(toIndentedString(childPublicID)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

