/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * NegotiationDetail
 */
@JsonPropertyOrder({
  NegotiationDetail.JSON_PROPERTY_ITEM_IDENTIFIER,
  NegotiationDetail.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  NegotiationDetail.JSON_PROPERTY_NEGOTIATION_X_M_L,
  NegotiationDetail.JSON_PROPERTY_NEGOTIATION_SECTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class NegotiationDetail {
  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NEGOTIATION_X_M_L = "negotiationXML";
  private JsonNullable<String> negotiationXML = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NEGOTIATION_SECTION = "negotiationSection";
  private JsonNullable<String> negotiationSection = JsonNullable.<String>undefined();


  public NegotiationDetail itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public NegotiationDetail ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public NegotiationDetail negotiationXML(String negotiationXML) {
    this.negotiationXML = JsonNullable.<String>of(negotiationXML);
    
    return this;
  }

   /**
   * Get negotiationXML
   * @return negotiationXML
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getNegotiationXML() {
        return negotiationXML.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEGOTIATION_X_M_L)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getNegotiationXML_JsonNullable() {
    return negotiationXML;
  }
  
  @JsonProperty(JSON_PROPERTY_NEGOTIATION_X_M_L)
  public void setNegotiationXML_JsonNullable(JsonNullable<String> negotiationXML) {
    this.negotiationXML = negotiationXML;
  }

  public void setNegotiationXML(String negotiationXML) {
    this.negotiationXML = JsonNullable.<String>of(negotiationXML);
  }


  public NegotiationDetail negotiationSection(String negotiationSection) {
    this.negotiationSection = JsonNullable.<String>of(negotiationSection);
    
    return this;
  }

   /**
   * Get negotiationSection
   * @return negotiationSection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getNegotiationSection() {
        return negotiationSection.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEGOTIATION_SECTION)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getNegotiationSection_JsonNullable() {
    return negotiationSection;
  }
  
  @JsonProperty(JSON_PROPERTY_NEGOTIATION_SECTION)
  public void setNegotiationSection_JsonNullable(JsonNullable<String> negotiationSection) {
    this.negotiationSection = negotiationSection;
  }

  public void setNegotiationSection(String negotiationSection) {
    this.negotiationSection = JsonNullable.<String>of(negotiationSection);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NegotiationDetail negotiationDetail = (NegotiationDetail) o;
    return Objects.equals(this.itemIdentifier, negotiationDetail.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, negotiationDetail.ancestorItemIdentifier) &&
        Objects.equals(this.negotiationXML, negotiationDetail.negotiationXML) &&
        Objects.equals(this.negotiationSection, negotiationDetail.negotiationSection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIdentifier, ancestorItemIdentifier, negotiationXML, negotiationSection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NegotiationDetail {\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    negotiationXML: ").append(toIndentedString(negotiationXML)).append("\n");
    sb.append("    negotiationSection: ").append(toIndentedString(negotiationSection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

