/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * VirtualProductLine
 */
@JsonPropertyOrder({
  VirtualProductLine.JSON_PROPERTY_ITEM_IDENTIFIER,
  VirtualProductLine.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  VirtualProductLine.JSON_PROPERTY_PURGE,
  VirtualProductLine.JSON_PROPERTY_RETIRED,
  VirtualProductLine.JSON_PROPERTY_LINE_CODE,
  VirtualProductLine.JSON_PROPERTY_LINE_AVAILABLE,
  VirtualProductLine.JSON_PROPERTY_VIRTUAL_PRODUCT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class VirtualProductLine {
  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PURGE = "purge";
  private Boolean purge;

  public static final String JSON_PROPERTY_RETIRED = "retired";
  private Boolean retired;

  public static final String JSON_PROPERTY_LINE_CODE = "lineCode";
  private String lineCode;

  public static final String JSON_PROPERTY_LINE_AVAILABLE = "lineAvailable";
  private Boolean lineAvailable;

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT = "virtualProduct";
  private JsonNullable<String> virtualProduct = JsonNullable.<String>undefined();


  public VirtualProductLine itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public VirtualProductLine ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public VirtualProductLine purge(Boolean purge) {
    
    this.purge = purge;
    return this;
  }

   /**
   * Get purge
   * @return purge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PURGE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getPurge() {
    return purge;
  }


  public void setPurge(Boolean purge) {
    this.purge = purge;
  }


  public VirtualProductLine retired(Boolean retired) {
    
    this.retired = retired;
    return this;
  }

   /**
   * Get retired
   * @return retired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETIRED)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getRetired() {
    return retired;
  }


  public void setRetired(Boolean retired) {
    this.retired = retired;
  }


  public VirtualProductLine lineCode(String lineCode) {
    
    this.lineCode = lineCode;
    return this;
  }

   /**
   * Get lineCode
   * @return lineCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINE_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getLineCode() {
    return lineCode;
  }


  public void setLineCode(String lineCode) {
    this.lineCode = lineCode;
  }


  public VirtualProductLine lineAvailable(Boolean lineAvailable) {
    
    this.lineAvailable = lineAvailable;
    return this;
  }

   /**
   * Get lineAvailable
   * @return lineAvailable
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LINE_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLineAvailable() {
    return lineAvailable;
  }


  public void setLineAvailable(Boolean lineAvailable) {
    this.lineAvailable = lineAvailable;
  }


  public VirtualProductLine virtualProduct(String virtualProduct) {
    this.virtualProduct = JsonNullable.<String>of(virtualProduct);
    
    return this;
  }

   /**
   * Get virtualProduct
   * @return virtualProduct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getVirtualProduct() {
        return virtualProduct.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getVirtualProduct_JsonNullable() {
    return virtualProduct;
  }
  
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT)
  public void setVirtualProduct_JsonNullable(JsonNullable<String> virtualProduct) {
    this.virtualProduct = virtualProduct;
  }

  public void setVirtualProduct(String virtualProduct) {
    this.virtualProduct = JsonNullable.<String>of(virtualProduct);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualProductLine virtualProductLine = (VirtualProductLine) o;
    return Objects.equals(this.itemIdentifier, virtualProductLine.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, virtualProductLine.ancestorItemIdentifier) &&
        Objects.equals(this.purge, virtualProductLine.purge) &&
        Objects.equals(this.retired, virtualProductLine.retired) &&
        Objects.equals(this.lineCode, virtualProductLine.lineCode) &&
        Objects.equals(this.lineAvailable, virtualProductLine.lineAvailable) &&
        Objects.equals(this.virtualProduct, virtualProductLine.virtualProduct);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIdentifier, ancestorItemIdentifier, purge, retired, lineCode, lineAvailable, virtualProduct);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualProductLine {\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    purge: ").append(toIndentedString(purge)).append("\n");
    sb.append("    retired: ").append(toIndentedString(retired)).append("\n");
    sb.append("    lineCode: ").append(toIndentedString(lineCode)).append("\n");
    sb.append("    lineAvailable: ").append(toIndentedString(lineAvailable)).append("\n");
    sb.append("    virtualProduct: ").append(toIndentedString(virtualProduct)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

