/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import pmp.sdk.model.VirtualProductCategory;
import pmp.sdk.model.VirtualProductContract;
import pmp.sdk.model.VirtualProductFlavour;
import pmp.sdk.model.VirtualProductLine;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * VirtualProduct
 */
@JsonPropertyOrder({
  VirtualProduct.JSON_PROPERTY_EFFECTIVE_DATE,
  VirtualProduct.JSON_PROPERTY_EXPIRATION_DATE,
  VirtualProduct.JSON_PROPERTY_CODE,
  VirtualProduct.JSON_PROPERTY_LOCKED,
  VirtualProduct.JSON_PROPERTY_JSON_STRING,
  VirtualProduct.JSON_PROPERTY_ITEM_IDENTIFIER,
  VirtualProduct.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  VirtualProduct.JSON_PROPERTY_VERSION_NUMBER,
  VirtualProduct.JSON_PROPERTY_ITEM_STATUS,
  VirtualProduct.JSON_PROPERTY_NAME,
  VirtualProduct.JSON_PROPERTY_PRODUCT_CODE,
  VirtualProduct.JSON_PROPERTY_ALLOW_AFFINITY,
  VirtualProduct.JSON_PROPERTY_ALLOW_CAMPAIGN,
  VirtualProduct.JSON_PROPERTY_VIRTUAL_PRODUCT_TYPE,
  VirtualProduct.JSON_PROPERTY_VIRTUAL_PRODUCT_CATEGORIES,
  VirtualProduct.JSON_PROPERTY_VIRTUAL_PRODUCT_CONTRACTS,
  VirtualProduct.JSON_PROPERTY_VIRTUAL_PRODUCT_FLAVOURS,
  VirtualProduct.JSON_PROPERTY_VIRTUAL_PRODUCT_LINES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class VirtualProduct {
  public static final String JSON_PROPERTY_EFFECTIVE_DATE = "effectiveDate";
  private String effectiveDate;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  private JsonNullable<String> expirationDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_LOCKED = "locked";
  private Boolean locked;

  public static final String JSON_PROPERTY_JSON_STRING = "jsonString";
  private JsonNullable<String> jsonString = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VERSION_NUMBER = "versionNumber";
  private Integer versionNumber;

  /**
   * Gets or Sets itemStatus
   */
  public enum ItemStatusEnum {
    DRAFT("draft"),
    
    STAGE("stage"),
    
    APPROVED("approved");

    private String value;

    ItemStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ItemStatusEnum fromValue(String value) {
      for (ItemStatusEnum b : ItemStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ITEM_STATUS = "itemStatus";
  private ItemStatusEnum itemStatus;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PRODUCT_CODE = "productCode";
  private String productCode;

  public static final String JSON_PROPERTY_ALLOW_AFFINITY = "allowAffinity";
  private Boolean allowAffinity;

  public static final String JSON_PROPERTY_ALLOW_CAMPAIGN = "allowCampaign";
  private Boolean allowCampaign;

  /**
   * Gets or Sets virtualProductType
   */
  public enum VirtualProductTypeEnum {
    OPEN("open"),
    
    CLOSED("closed"),
    
    GENERALAGREEMENT("generalagreement");

    private String value;

    VirtualProductTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VirtualProductTypeEnum fromValue(String value) {
      for (VirtualProductTypeEnum b : VirtualProductTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT_TYPE = "VirtualProductType";
  private VirtualProductTypeEnum virtualProductType;

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT_CATEGORIES = "virtualProductCategories";
  private List<VirtualProductCategory> virtualProductCategories = new ArrayList<>();

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT_CONTRACTS = "virtualProductContracts";
  private List<VirtualProductContract> virtualProductContracts = new ArrayList<>();

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT_FLAVOURS = "virtualProductFlavours";
  private List<VirtualProductFlavour> virtualProductFlavours = new ArrayList<>();

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT_LINES = "virtualProductLines";
  private List<VirtualProductLine> virtualProductLines = new ArrayList<>();


  public VirtualProduct effectiveDate(String effectiveDate) {
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Get effectiveDate
   * @return effectiveDate
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }


  public VirtualProduct expirationDate(String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
    
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getExpirationDate() {
        return expirationDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getExpirationDate_JsonNullable() {
    return expirationDate;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  public void setExpirationDate_JsonNullable(JsonNullable<String> expirationDate) {
    this.expirationDate = expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
  }


  public VirtualProduct code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public VirtualProduct locked(Boolean locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getLocked() {
    return locked;
  }


  public void setLocked(Boolean locked) {
    this.locked = locked;
  }


  public VirtualProduct jsonString(String jsonString) {
    this.jsonString = JsonNullable.<String>of(jsonString);
    
    return this;
  }

   /**
   * Get jsonString
   * @return jsonString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getJsonString() {
        return jsonString.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JSON_STRING)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getJsonString_JsonNullable() {
    return jsonString;
  }
  
  @JsonProperty(JSON_PROPERTY_JSON_STRING)
  public void setJsonString_JsonNullable(JsonNullable<String> jsonString) {
    this.jsonString = jsonString;
  }

  public void setJsonString(String jsonString) {
    this.jsonString = JsonNullable.<String>of(jsonString);
  }


  public VirtualProduct itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public VirtualProduct ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public VirtualProduct versionNumber(Integer versionNumber) {
    
    this.versionNumber = versionNumber;
    return this;
  }

   /**
   * Get versionNumber
   * minimum: -2147483648
   * maximum: 2147483647
   * @return versionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Integer getVersionNumber() {
    return versionNumber;
  }


  public void setVersionNumber(Integer versionNumber) {
    this.versionNumber = versionNumber;
  }


  public VirtualProduct itemStatus(ItemStatusEnum itemStatus) {
    
    this.itemStatus = itemStatus;
    return this;
  }

   /**
   * Get itemStatus
   * @return itemStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_STATUS)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public ItemStatusEnum getItemStatus() {
    return itemStatus;
  }


  public void setItemStatus(ItemStatusEnum itemStatus) {
    this.itemStatus = itemStatus;
  }


  public VirtualProduct name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VirtualProduct productCode(String productCode) {
    
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_CODE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public String getProductCode() {
    return productCode;
  }


  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  public VirtualProduct allowAffinity(Boolean allowAffinity) {
    
    this.allowAffinity = allowAffinity;
    return this;
  }

   /**
   * Get allowAffinity
   * @return allowAffinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALLOW_AFFINITY)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getAllowAffinity() {
    return allowAffinity;
  }


  public void setAllowAffinity(Boolean allowAffinity) {
    this.allowAffinity = allowAffinity;
  }


  public VirtualProduct allowCampaign(Boolean allowCampaign) {
    
    this.allowCampaign = allowCampaign;
    return this;
  }

   /**
   * Get allowCampaign
   * @return allowCampaign
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALLOW_CAMPAIGN)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getAllowCampaign() {
    return allowCampaign;
  }


  public void setAllowCampaign(Boolean allowCampaign) {
    this.allowCampaign = allowCampaign;
  }


  public VirtualProduct virtualProductType(VirtualProductTypeEnum virtualProductType) {
    
    this.virtualProductType = virtualProductType;
    return this;
  }

   /**
   * Get virtualProductType
   * @return virtualProductType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT_TYPE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public VirtualProductTypeEnum getVirtualProductType() {
    return virtualProductType;
  }


  public void setVirtualProductType(VirtualProductTypeEnum virtualProductType) {
    this.virtualProductType = virtualProductType;
  }


  public VirtualProduct virtualProductCategories(List<VirtualProductCategory> virtualProductCategories) {
    
    this.virtualProductCategories = virtualProductCategories;
    return this;
  }

  public VirtualProduct addVirtualProductCategoriesItem(VirtualProductCategory virtualProductCategoriesItem) {
    this.virtualProductCategories.add(virtualProductCategoriesItem);
    return this;
  }

   /**
   * Get virtualProductCategories
   * @return virtualProductCategories
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VirtualProductCategory> getVirtualProductCategories() {
    return virtualProductCategories;
  }


  public void setVirtualProductCategories(List<VirtualProductCategory> virtualProductCategories) {
    this.virtualProductCategories = virtualProductCategories;
  }


  public VirtualProduct virtualProductContracts(List<VirtualProductContract> virtualProductContracts) {
    
    this.virtualProductContracts = virtualProductContracts;
    return this;
  }

  public VirtualProduct addVirtualProductContractsItem(VirtualProductContract virtualProductContractsItem) {
    this.virtualProductContracts.add(virtualProductContractsItem);
    return this;
  }

   /**
   * Get virtualProductContracts
   * @return virtualProductContracts
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT_CONTRACTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VirtualProductContract> getVirtualProductContracts() {
    return virtualProductContracts;
  }


  public void setVirtualProductContracts(List<VirtualProductContract> virtualProductContracts) {
    this.virtualProductContracts = virtualProductContracts;
  }


  public VirtualProduct virtualProductFlavours(List<VirtualProductFlavour> virtualProductFlavours) {
    
    this.virtualProductFlavours = virtualProductFlavours;
    return this;
  }

  public VirtualProduct addVirtualProductFlavoursItem(VirtualProductFlavour virtualProductFlavoursItem) {
    this.virtualProductFlavours.add(virtualProductFlavoursItem);
    return this;
  }

   /**
   * Get virtualProductFlavours
   * @return virtualProductFlavours
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT_FLAVOURS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VirtualProductFlavour> getVirtualProductFlavours() {
    return virtualProductFlavours;
  }


  public void setVirtualProductFlavours(List<VirtualProductFlavour> virtualProductFlavours) {
    this.virtualProductFlavours = virtualProductFlavours;
  }


  public VirtualProduct virtualProductLines(List<VirtualProductLine> virtualProductLines) {
    
    this.virtualProductLines = virtualProductLines;
    return this;
  }

  public VirtualProduct addVirtualProductLinesItem(VirtualProductLine virtualProductLinesItem) {
    this.virtualProductLines.add(virtualProductLinesItem);
    return this;
  }

   /**
   * Get virtualProductLines
   * @return virtualProductLines
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT_LINES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VirtualProductLine> getVirtualProductLines() {
    return virtualProductLines;
  }


  public void setVirtualProductLines(List<VirtualProductLine> virtualProductLines) {
    this.virtualProductLines = virtualProductLines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualProduct virtualProduct = (VirtualProduct) o;
    return Objects.equals(this.effectiveDate, virtualProduct.effectiveDate) &&
        Objects.equals(this.expirationDate, virtualProduct.expirationDate) &&
        Objects.equals(this.code, virtualProduct.code) &&
        Objects.equals(this.locked, virtualProduct.locked) &&
        Objects.equals(this.jsonString, virtualProduct.jsonString) &&
        Objects.equals(this.itemIdentifier, virtualProduct.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, virtualProduct.ancestorItemIdentifier) &&
        Objects.equals(this.versionNumber, virtualProduct.versionNumber) &&
        Objects.equals(this.itemStatus, virtualProduct.itemStatus) &&
        Objects.equals(this.name, virtualProduct.name) &&
        Objects.equals(this.productCode, virtualProduct.productCode) &&
        Objects.equals(this.allowAffinity, virtualProduct.allowAffinity) &&
        Objects.equals(this.allowCampaign, virtualProduct.allowCampaign) &&
        Objects.equals(this.virtualProductType, virtualProduct.virtualProductType) &&
        Objects.equals(this.virtualProductCategories, virtualProduct.virtualProductCategories) &&
        Objects.equals(this.virtualProductContracts, virtualProduct.virtualProductContracts) &&
        Objects.equals(this.virtualProductFlavours, virtualProduct.virtualProductFlavours) &&
        Objects.equals(this.virtualProductLines, virtualProduct.virtualProductLines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveDate, expirationDate, code, locked, jsonString, itemIdentifier, ancestorItemIdentifier, versionNumber, itemStatus, name, productCode, allowAffinity, allowCampaign, virtualProductType, virtualProductCategories, virtualProductContracts, virtualProductFlavours, virtualProductLines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualProduct {\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    jsonString: ").append(toIndentedString(jsonString)).append("\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    itemStatus: ").append(toIndentedString(itemStatus)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    allowAffinity: ").append(toIndentedString(allowAffinity)).append("\n");
    sb.append("    allowCampaign: ").append(toIndentedString(allowCampaign)).append("\n");
    sb.append("    virtualProductType: ").append(toIndentedString(virtualProductType)).append("\n");
    sb.append("    virtualProductCategories: ").append(toIndentedString(virtualProductCategories)).append("\n");
    sb.append("    virtualProductContracts: ").append(toIndentedString(virtualProductContracts)).append("\n");
    sb.append("    virtualProductFlavours: ").append(toIndentedString(virtualProductFlavours)).append("\n");
    sb.append("    virtualProductLines: ").append(toIndentedString(virtualProductLines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

