/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * VirtualProductContract
 */
@JsonPropertyOrder({
  VirtualProductContract.JSON_PROPERTY_ITEM_IDENTIFIER,
  VirtualProductContract.JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER,
  VirtualProductContract.JSON_PROPERTY_PURGE,
  VirtualProductContract.JSON_PROPERTY_RETIRED,
  VirtualProductContract.JSON_PROPERTY_PRIORITY,
  VirtualProductContract.JSON_PROPERTY_CONTRACT_IDENTIFIER,
  VirtualProductContract.JSON_PROPERTY_VIRTUAL_PRODUCT,
  VirtualProductContract.JSON_PROPERTY_CONTRACT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-30T00:50:45.283009+02:00[Europe/Warsaw]")
public class VirtualProductContract {
  public static final String JSON_PROPERTY_ITEM_IDENTIFIER = "itemIdentifier";
  private String itemIdentifier;

  public static final String JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER = "ancestorItemIdentifier";
  private JsonNullable<String> ancestorItemIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PURGE = "purge";
  private Boolean purge;

  public static final String JSON_PROPERTY_RETIRED = "retired";
  private Boolean retired;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private JsonNullable<Integer> priority = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CONTRACT_IDENTIFIER = "contractIdentifier";
  private JsonNullable<String> contractIdentifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VIRTUAL_PRODUCT = "virtualProduct";
  private JsonNullable<String> virtualProduct = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CONTRACT = "contract";
  private JsonNullable<String> contract = JsonNullable.<String>undefined();


  public VirtualProductContract itemIdentifier(String itemIdentifier) {
    
    this.itemIdentifier = itemIdentifier;
    return this;
  }

   /**
   * Get itemIdentifier
   * @return itemIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemIdentifier() {
    return itemIdentifier;
  }


  public void setItemIdentifier(String itemIdentifier) {
    this.itemIdentifier = itemIdentifier;
  }


  public VirtualProductContract ancestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
    
    return this;
  }

   /**
   * Get ancestorItemIdentifier
   * @return ancestorItemIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getAncestorItemIdentifier() {
        return ancestorItemIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getAncestorItemIdentifier_JsonNullable() {
    return ancestorItemIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_ANCESTOR_ITEM_IDENTIFIER)
  public void setAncestorItemIdentifier_JsonNullable(JsonNullable<String> ancestorItemIdentifier) {
    this.ancestorItemIdentifier = ancestorItemIdentifier;
  }

  public void setAncestorItemIdentifier(String ancestorItemIdentifier) {
    this.ancestorItemIdentifier = JsonNullable.<String>of(ancestorItemIdentifier);
  }


  public VirtualProductContract purge(Boolean purge) {
    
    this.purge = purge;
    return this;
  }

   /**
   * Get purge
   * @return purge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PURGE)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getPurge() {
    return purge;
  }


  public void setPurge(Boolean purge) {
    this.purge = purge;
  }


  public VirtualProductContract retired(Boolean retired) {
    
    this.retired = retired;
    return this;
  }

   /**
   * Get retired
   * @return retired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETIRED)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public Boolean getRetired() {
    return retired;
  }


  public void setRetired(Boolean retired) {
    this.retired = retired;
  }


  public VirtualProductContract priority(Integer priority) {
    this.priority = JsonNullable.<Integer>of(priority);
    
    return this;
  }

   /**
   * Get priority
   * minimum: -2147483648
   * maximum: 2147483647
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getPriority() {
        return priority.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<Integer> getPriority_JsonNullable() {
    return priority;
  }
  
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  public void setPriority_JsonNullable(JsonNullable<Integer> priority) {
    this.priority = priority;
  }

  public void setPriority(Integer priority) {
    this.priority = JsonNullable.<Integer>of(priority);
  }


  public VirtualProductContract contractIdentifier(String contractIdentifier) {
    this.contractIdentifier = JsonNullable.<String>of(contractIdentifier);
    
    return this;
  }

   /**
   * Get contractIdentifier
   * @return contractIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getContractIdentifier() {
        return contractIdentifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTRACT_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getContractIdentifier_JsonNullable() {
    return contractIdentifier;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTRACT_IDENTIFIER)
  public void setContractIdentifier_JsonNullable(JsonNullable<String> contractIdentifier) {
    this.contractIdentifier = contractIdentifier;
  }

  public void setContractIdentifier(String contractIdentifier) {
    this.contractIdentifier = JsonNullable.<String>of(contractIdentifier);
  }


  public VirtualProductContract virtualProduct(String virtualProduct) {
    this.virtualProduct = JsonNullable.<String>of(virtualProduct);
    
    return this;
  }

   /**
   * Get virtualProduct
   * @return virtualProduct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getVirtualProduct() {
        return virtualProduct.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getVirtualProduct_JsonNullable() {
    return virtualProduct;
  }
  
  @JsonProperty(JSON_PROPERTY_VIRTUAL_PRODUCT)
  public void setVirtualProduct_JsonNullable(JsonNullable<String> virtualProduct) {
    this.virtualProduct = virtualProduct;
  }

  public void setVirtualProduct(String virtualProduct) {
    this.virtualProduct = JsonNullable.<String>of(virtualProduct);
  }


  public VirtualProductContract contract(String contract) {
    this.contract = JsonNullable.<String>of(contract);
    
    return this;
  }

   /**
   * Get contract
   * @return contract
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getContract() {
        return contract.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.NON_DEFAULT)

  public JsonNullable<String> getContract_JsonNullable() {
    return contract;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTRACT)
  public void setContract_JsonNullable(JsonNullable<String> contract) {
    this.contract = contract;
  }

  public void setContract(String contract) {
    this.contract = JsonNullable.<String>of(contract);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualProductContract virtualProductContract = (VirtualProductContract) o;
    return Objects.equals(this.itemIdentifier, virtualProductContract.itemIdentifier) &&
        Objects.equals(this.ancestorItemIdentifier, virtualProductContract.ancestorItemIdentifier) &&
        Objects.equals(this.purge, virtualProductContract.purge) &&
        Objects.equals(this.retired, virtualProductContract.retired) &&
        Objects.equals(this.priority, virtualProductContract.priority) &&
        Objects.equals(this.contractIdentifier, virtualProductContract.contractIdentifier) &&
        Objects.equals(this.virtualProduct, virtualProductContract.virtualProduct) &&
        Objects.equals(this.contract, virtualProductContract.contract);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIdentifier, ancestorItemIdentifier, purge, retired, priority, contractIdentifier, virtualProduct, contract);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualProductContract {\n");
    sb.append("    itemIdentifier: ").append(toIndentedString(itemIdentifier)).append("\n");
    sb.append("    ancestorItemIdentifier: ").append(toIndentedString(ancestorItemIdentifier)).append("\n");
    sb.append("    purge: ").append(toIndentedString(purge)).append("\n");
    sb.append("    retired: ").append(toIndentedString(retired)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    contractIdentifier: ").append(toIndentedString(contractIdentifier)).append("\n");
    sb.append("    virtualProduct: ").append(toIndentedString(virtualProduct)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

