/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Agreement
 */
public class AgreementTest {
    private final Agreement model = new Agreement();

    /**
     * Model tests for Agreement
     */
    @Test
    public void testAgreement() {
        // TODO: test Agreement
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'jsonString'
     */
    @Test
    public void jsonStringTest() {
        // TODO: test jsonString
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'itemStatus'
     */
    @Test
    public void itemStatusTest() {
        // TODO: test itemStatus
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'agreementNumber'
     */
    @Test
    public void agreementNumberTest() {
        // TODO: test agreementNumber
    }

    /**
     * Test the property 'acceptanceDate'
     */
    @Test
    public void acceptanceDateTest() {
        // TODO: test acceptanceDate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'customerAgreementNo'
     */
    @Test
    public void customerAgreementNoTest() {
        // TODO: test customerAgreementNo
    }

    /**
     * Test the property 'canceledDate'
     */
    @Test
    public void canceledDateTest() {
        // TODO: test canceledDate
    }

    /**
     * Test the property 'cancelReasonDesc'
     */
    @Test
    public void cancelReasonDescTest() {
        // TODO: test cancelReasonDesc
    }

    /**
     * Test the property 'cancelReason'
     */
    @Test
    public void cancelReasonTest() {
        // TODO: test cancelReason
    }

    /**
     * Test the property 'agreementStatus'
     */
    @Test
    public void agreementStatusTest() {
        // TODO: test agreementStatus
    }

    /**
     * Test the property 'agreementType'
     */
    @Test
    public void agreementTypeTest() {
        // TODO: test agreementType
    }

}
