/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractAttachment
 */
public class ContractAttachmentTest {
    private final ContractAttachment model = new ContractAttachment();

    /**
     * Model tests for ContractAttachment
     */
    @Test
    public void testContractAttachment() {
        // TODO: test ContractAttachment
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'coverableCode'
     */
    @Test
    public void coverableCodeTest() {
        // TODO: test coverableCode
    }

    /**
     * Test the property 'coverableIncluded'
     */
    @Test
    public void coverableIncludedTest() {
        // TODO: test coverableIncluded
    }

    /**
     * Test the property 'contractVersion'
     */
    @Test
    public void contractVersionTest() {
        // TODO: test contractVersion
    }

}
