/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import pmp.sdk.model.ContractAttachment;
import pmp.sdk.model.ContractCover;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractVersion
 */
public class ContractVersionTest {
    private final ContractVersion model = new ContractVersion();

    /**
     * Model tests for ContractVersion
     */
    @Test
    public void testContractVersion() {
        // TODO: test ContractVersion
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'contractAttachments'
     */
    @Test
    public void contractAttachmentsTest() {
        // TODO: test contractAttachments
    }

    /**
     * Test the property 'contractCovers'
     */
    @Test
    public void contractCoversTest() {
        // TODO: test contractCovers
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'hiddenContract'
     */
    @Test
    public void hiddenContractTest() {
        // TODO: test hiddenContract
    }

    /**
     * Test the property 'existence'
     */
    @Test
    public void existenceTest() {
        // TODO: test existence
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

}
