/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CoverageDependencyParent
 */
public class CoverageDependencyParentTest {
    private final CoverageDependencyParent model = new CoverageDependencyParent();

    /**
     * Model tests for CoverageDependencyParent
     */
    @Test
    public void testCoverageDependencyParent() {
        // TODO: test CoverageDependencyParent
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'coverageCode'
     */
    @Test
    public void coverageCodeTest() {
        // TODO: test coverageCode
    }

    /**
     * Test the property 'leftParenthesis'
     */
    @Test
    public void leftParenthesisTest() {
        // TODO: test leftParenthesis
    }

    /**
     * Test the property 'rightParenthesis'
     */
    @Test
    public void rightParenthesisTest() {
        // TODO: test rightParenthesis
    }

    /**
     * Test the property 'itemSequence'
     */
    @Test
    public void itemSequenceTest() {
        // TODO: test itemSequence
    }

    /**
     * Test the property 'conditionLogic'
     */
    @Test
    public void conditionLogicTest() {
        // TODO: test conditionLogic
    }

    /**
     * Test the property 'coverageDependency'
     */
    @Test
    public void coverageDependencyTest() {
        // TODO: test coverageDependency
    }

}
