/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExternalTermValue
 */
public class ExternalTermValueTest {
    private final ExternalTermValue model = new ExternalTermValue();

    /**
     * Model tests for ExternalTermValue
     */
    @Test
    public void testExternalTermValue() {
        // TODO: test ExternalTermValue
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'termCode'
     */
    @Test
    public void termCodeTest() {
        // TODO: test termCode
    }

    /**
     * Test the property 'termValue'
     */
    @Test
    public void termValueTest() {
        // TODO: test termValue
    }

    /**
     * Test the property 'clauseCode'
     */
    @Test
    public void clauseCodeTest() {
        // TODO: test clauseCode
    }

    /**
     * Test the property 'displayValue'
     */
    @Test
    public void displayValueTest() {
        // TODO: test displayValue
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'typelistName'
     */
    @Test
    public void typelistNameTest() {
        // TODO: test typelistName
    }

    /**
     * Test the property 'valueType'
     */
    @Test
    public void valueTypeTest() {
        // TODO: test valueType
    }

    /**
     * Test the property 'externalProduct'
     */
    @Test
    public void externalProductTest() {
        // TODO: test externalProduct
    }

}
