/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import pmp.sdk.model.ItemLinkDefinitionDetail;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ItemLinkDetail
 */
public class ItemLinkDetailTest {
    private final ItemLinkDetail model = new ItemLinkDetail();

    /**
     * Model tests for ItemLinkDetail
     */
    @Test
    public void testItemLinkDetail() {
        // TODO: test ItemLinkDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'itemLinkDefinitionDetail'
     */
    @Test
    public void itemLinkDefinitionDetailTest() {
        // TODO: test itemLinkDefinitionDetail
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'itemLink'
     */
    @Test
    public void itemLinkTest() {
        // TODO: test itemLink
    }

}
