/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import pmp.sdk.model.ItemLinkDetail;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ItemLink
 */
public class ItemLinkTest {
    private final ItemLink model = new ItemLink();

    /**
     * Model tests for ItemLink
     */
    @Test
    public void testItemLink() {
        // TODO: test ItemLink
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'itemLinkDetails'
     */
    @Test
    public void itemLinkDetailsTest() {
        // TODO: test itemLinkDetails
    }

    /**
     * Test the property 'parentType'
     */
    @Test
    public void parentTypeTest() {
        // TODO: test parentType
    }

    /**
     * Test the property 'parentCode'
     */
    @Test
    public void parentCodeTest() {
        // TODO: test parentCode
    }

    /**
     * Test the property 'parentSubCode'
     */
    @Test
    public void parentSubCodeTest() {
        // TODO: test parentSubCode
    }

    /**
     * Test the property 'parentVersionNumber'
     */
    @Test
    public void parentVersionNumberTest() {
        // TODO: test parentVersionNumber
    }

    /**
     * Test the property 'parentItemIdentifier'
     */
    @Test
    public void parentItemIdentifierTest() {
        // TODO: test parentItemIdentifier
    }

    /**
     * Test the property 'parentSecondaryIdentifier'
     */
    @Test
    public void parentSecondaryIdentifierTest() {
        // TODO: test parentSecondaryIdentifier
    }

    /**
     * Test the property 'parentPublicID'
     */
    @Test
    public void parentPublicIDTest() {
        // TODO: test parentPublicID
    }

    /**
     * Test the property 'childType'
     */
    @Test
    public void childTypeTest() {
        // TODO: test childType
    }

    /**
     * Test the property 'childCode'
     */
    @Test
    public void childCodeTest() {
        // TODO: test childCode
    }

    /**
     * Test the property 'childSubCode'
     */
    @Test
    public void childSubCodeTest() {
        // TODO: test childSubCode
    }

    /**
     * Test the property 'childVersionNumber'
     */
    @Test
    public void childVersionNumberTest() {
        // TODO: test childVersionNumber
    }

    /**
     * Test the property 'childItemIdentifier'
     */
    @Test
    public void childItemIdentifierTest() {
        // TODO: test childItemIdentifier
    }

    /**
     * Test the property 'childSecondaryIdentifier'
     */
    @Test
    public void childSecondaryIdentifierTest() {
        // TODO: test childSecondaryIdentifier
    }

    /**
     * Test the property 'childPublicID'
     */
    @Test
    public void childPublicIDTest() {
        // TODO: test childPublicID
    }

    /**
     * Test the property 'removed'
     */
    @Test
    public void removedTest() {
        // TODO: test removed
    }

}
