/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import pmp.sdk.model.NegotiationSection;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Negotiation
 */
public class NegotiationTest {
    private final Negotiation model = new Negotiation();

    /**
     * Model tests for Negotiation
     */
    @Test
    public void testNegotiation() {
        // TODO: test Negotiation
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'negotiationSections'
     */
    @Test
    public void negotiationSectionsTest() {
        // TODO: test negotiationSections
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'jsonString'
     */
    @Test
    public void jsonStringTest() {
        // TODO: test jsonString
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'itemStatus'
     */
    @Test
    public void itemStatusTest() {
        // TODO: test itemStatus
    }

    /**
     * Test the property 'individualPolicies'
     */
    @Test
    public void individualPoliciesTest() {
        // TODO: test individualPolicies
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'negotiationStatus'
     */
    @Test
    public void negotiationStatusTest() {
        // TODO: test negotiationStatus
    }

}
