/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SchemeConditionParam
 */
public class SchemeConditionParamTest {
    private final SchemeConditionParam model = new SchemeConditionParam();

    /**
     * Model tests for SchemeConditionParam
     */
    @Test
    public void testSchemeConditionParam() {
        // TODO: test SchemeConditionParam
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    public void parameterTest() {
        // TODO: test parameter
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'paramValueType'
     */
    @Test
    public void paramValueTypeTest() {
        // TODO: test paramValueType
    }

    /**
     * Test the property 'schemeCondition'
     */
    @Test
    public void schemeConditionTest() {
        // TODO: test schemeCondition
    }

}
