/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import pmp.sdk.model.SchemeDetailArrayValue;
import pmp.sdk.model.SchemeDetailParam;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SchemeDetail
 */
public class SchemeDetailTest {
    private final SchemeDetail model = new SchemeDetail();

    /**
     * Model tests for SchemeDetail
     */
    @Test
    public void testSchemeDetail() {
        // TODO: test SchemeDetail
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'schemeDetailParams'
     */
    @Test
    public void schemeDetailParamsTest() {
        // TODO: test schemeDetailParams
    }

    /**
     * Test the property 'schemeDetailArrayValues'
     */
    @Test
    public void schemeDetailArrayValuesTest() {
        // TODO: test schemeDetailArrayValues
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'stringValue'
     */
    @Test
    public void stringValueTest() {
        // TODO: test stringValue
    }

    /**
     * Test the property 'booleanValue'
     */
    @Test
    public void booleanValueTest() {
        // TODO: test booleanValue
    }

    /**
     * Test the property 'dateValue'
     */
    @Test
    public void dateValueTest() {
        // TODO: test dateValue
    }

    /**
     * Test the property 'integerValue'
     */
    @Test
    public void integerValueTest() {
        // TODO: test integerValue
    }

    /**
     * Test the property 'decimalValue'
     */
    @Test
    public void decimalValueTest() {
        // TODO: test decimalValue
    }

    /**
     * Test the property 'moneyValue'
     */
    @Test
    public void moneyValueTest() {
        // TODO: test moneyValue
    }

    /**
     * Test the property 'schemeCalcValueType'
     */
    @Test
    public void schemeCalcValueTypeTest() {
        // TODO: test schemeCalcValueType
    }

    /**
     * Test the property 'comparator'
     */
    @Test
    public void comparatorTest() {
        // TODO: test comparator
    }

    /**
     * Test the property 'parentCode'
     */
    @Test
    public void parentCodeTest() {
        // TODO: test parentCode
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'forceValue'
     */
    @Test
    public void forceValueTest() {
        // TODO: test forceValue
    }

    /**
     * Test the property 'timeDuration'
     */
    @Test
    public void timeDurationTest() {
        // TODO: test timeDuration
    }

    /**
     * Test the property 'costDiscount'
     */
    @Test
    public void costDiscountTest() {
        // TODO: test costDiscount
    }

    /**
     * Test the property 'minMax'
     */
    @Test
    public void minMaxTest() {
        // TODO: test minMax
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'schemeCostType'
     */
    @Test
    public void schemeCostTypeTest() {
        // TODO: test schemeCostType
    }

    /**
     * Test the property 'schemeOperatorType'
     */
    @Test
    public void schemeOperatorTypeTest() {
        // TODO: test schemeOperatorType
    }

    /**
     * Test the property 'schemeSourceType'
     */
    @Test
    public void schemeSourceTypeTest() {
        // TODO: test schemeSourceType
    }

    /**
     * Test the property 'schemeTimeframe'
     */
    @Test
    public void schemeTimeframeTest() {
        // TODO: test schemeTimeframe
    }

    /**
     * Test the property 'schemeValueType'
     */
    @Test
    public void schemeValueTypeTest() {
        // TODO: test schemeValueType
    }

    /**
     * Test the property 'schemeValidationType'
     */
    @Test
    public void schemeValidationTypeTest() {
        // TODO: test schemeValidationType
    }

    /**
     * Test the property 'scheme'
     */
    @Test
    public void schemeTest() {
        // TODO: test scheme
    }

}
