/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import pmp.sdk.model.SchemeConditionParam;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SchemeDetailParam
 */
public class SchemeDetailParamTest {
    private final SchemeDetailParam model = new SchemeDetailParam();

    /**
     * Model tests for SchemeDetailParam
     */
    @Test
    public void testSchemeDetailParam() {
        // TODO: test SchemeDetailParam
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'schemeConditionParam'
     */
    @Test
    public void schemeConditionParamTest() {
        // TODO: test schemeConditionParam
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'stringValue'
     */
    @Test
    public void stringValueTest() {
        // TODO: test stringValue
    }

    /**
     * Test the property 'booleanValue'
     */
    @Test
    public void booleanValueTest() {
        // TODO: test booleanValue
    }

    /**
     * Test the property 'dateValue'
     */
    @Test
    public void dateValueTest() {
        // TODO: test dateValue
    }

    /**
     * Test the property 'integerValue'
     */
    @Test
    public void integerValueTest() {
        // TODO: test integerValue
    }

    /**
     * Test the property 'decimalValue'
     */
    @Test
    public void decimalValueTest() {
        // TODO: test decimalValue
    }

    /**
     * Test the property 'moneyValue'
     */
    @Test
    public void moneyValueTest() {
        // TODO: test moneyValue
    }

    /**
     * Test the property 'schemeCalcValueType'
     */
    @Test
    public void schemeCalcValueTypeTest() {
        // TODO: test schemeCalcValueType
    }

    /**
     * Test the property 'schemeDetail'
     */
    @Test
    public void schemeDetailTest() {
        // TODO: test schemeDetail
    }

}
