/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import pmp.sdk.model.VirtualProductCategory;
import pmp.sdk.model.VirtualProductContract;
import pmp.sdk.model.VirtualProductFlavour;
import pmp.sdk.model.VirtualProductLine;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VirtualProduct
 */
public class VirtualProductTest {
    private final VirtualProduct model = new VirtualProduct();

    /**
     * Model tests for VirtualProduct
     */
    @Test
    public void testVirtualProduct() {
        // TODO: test VirtualProduct
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'virtualProductCategories'
     */
    @Test
    public void virtualProductCategoriesTest() {
        // TODO: test virtualProductCategories
    }

    /**
     * Test the property 'virtualProductContracts'
     */
    @Test
    public void virtualProductContractsTest() {
        // TODO: test virtualProductContracts
    }

    /**
     * Test the property 'virtualProductFlavours'
     */
    @Test
    public void virtualProductFlavoursTest() {
        // TODO: test virtualProductFlavours
    }

    /**
     * Test the property 'virtualProductLines'
     */
    @Test
    public void virtualProductLinesTest() {
        // TODO: test virtualProductLines
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'jsonString'
     */
    @Test
    public void jsonStringTest() {
        // TODO: test jsonString
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'itemStatus'
     */
    @Test
    public void itemStatusTest() {
        // TODO: test itemStatus
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'allowAffinity'
     */
    @Test
    public void allowAffinityTest() {
        // TODO: test allowAffinity
    }

    /**
     * Test the property 'allowCampaign'
     */
    @Test
    public void allowCampaignTest() {
        // TODO: test allowCampaign
    }

    /**
     * Test the property 'virtualProductType'
     */
    @Test
    public void virtualProductTypeTest() {
        // TODO: test virtualProductType
    }

}
