/*
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pmp.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VirtualProductLine
 */
public class VirtualProductLineTest {
    private final VirtualProductLine model = new VirtualProductLine();

    /**
     * Model tests for VirtualProductLine
     */
    @Test
    public void testVirtualProductLine() {
        // TODO: test VirtualProductLine
    }

    /**
     * Test the property 'itemIdentifierInternal'
     */
    @Test
    public void itemIdentifierInternalTest() {
        // TODO: test itemIdentifierInternal
    }

    /**
     * Test the property 'ancestorItemIdentifier'
     */
    @Test
    public void ancestorItemIdentifierTest() {
        // TODO: test ancestorItemIdentifier
    }

    /**
     * Test the property 'lineCode'
     */
    @Test
    public void lineCodeTest() {
        // TODO: test lineCode
    }

    /**
     * Test the property 'lineAvailable'
     */
    @Test
    public void lineAvailableTest() {
        // TODO: test lineAvailable
    }

    /**
     * Test the property 'virtualProduct'
     */
    @Test
    public void virtualProductTest() {
        // TODO: test virtualProduct
    }

}
